#########################
## Sample Sass Lint File
#########################
# Linter Options
# options:
  # Don't merge default rules
  # merge-default-rules: false
  # Set the formatter to 'html'
  # formatter: html
  # Output file instead of logging results
  # output-file: 'linters/sass-lint.html'
# File Options
files:
  include: 'src/main/client/**/*.s+(a|c)ss'
  ignore:
    - '**/vendor.s+(a|c)ss'
    - 'node_modules/**'
# Rule Configuration
rules:
  no-duplicate-properties:
    - 0   # 0 switched off because we sometimes need browser specific rules
  clean-import-paths:
    - 0 # 0 switched off because we use partials scss http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials
  nesting-depth:
    - 1
    -
      max-depth: 4
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  # no-warn: 1
  # no-debug: 1
  no-ids: 2
  no-important: 0
  no-vendor-prefixes: 0
  no-color-literals: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  # variable-for-property:
  #   - 1
  #   -
  #     properties:
  #       - margin
  #       - content
  single-line-per-selector: 0
